# Generated by Django 5.0.6 on 2024-06-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
